repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master]
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.3.347
    hooks:
      - id: checkov
        args: [--quiet]
