apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "{{ .Release.Name }}-ip-bool"
spec:
  blocks:
  - cidr: {{ .Values.cidr }}
  allowFirstLastIPs: "{{ .Values.allowFirstLastIPs }}"